build:
  nodes:
    coverage:
      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover="coverage.xml"
            coverage:
              file: coverage.xml   # <- Set this to where we find the coverage data.
              #    The path is relative to the current directory.
              format: clover
